'use strict';
const letterWords=['To the bearer of my invitation,','If I am delayed, follow the light.','You will find a way onward.','S. V.'];
notes.letter=['給持邀請函而來的人','「致持邀請函而來的人：\n若我耽擱了，請循著光。你會找到繼續前行的路。\nS. V.」\n這封信的確是給你的。只是主人似乎寧願留下一點謎語，也不肯直接說明自己在哪裡。'];
if(state.finished)state.corridorHandleTried=true;
if(state.keyTagRead){state.hallFootstepsInvestigated=true;state.keyReviewSuggested=true;}
function keyReviewReady(){return !!(state.keyOwned&&state.stairSurveyDone&&state.keyTried&&state.hallFootstepsInvestigated);}
const baseGo36=go;
go=function(id){if(id==='exterior'&&state.receptionDone)id='foyer';const from=state.scene;if(id==='hall'&&['gallery','stairwell','door'].includes(from)&&state.hallFootstepsHeard)state.hallFootstepsInvestigated=true;if(id==='room'&&keyReviewReady())state.keyReviewSuggested=true;baseGo36(id);};
$('resume').onclick=()=>{audioInit();loadFoley();if(state.receptionDone){go('hall');caption('你提穩手中的燭台，重新站在前廳。\n先前找到的線索和隨身物品都還在。')}else{go(state.scene);if(['hall','foyer'].includes(state.scene))reception()}};
const baseNav36=sceneNavigation;
sceneNavigation=function(id){const nav=baseNav36(id).filter(([a])=>!(a==='door'&&['room','desk','window'].includes(id)&&!state.corridorNoticed&&!state.seen.includes('door')));if(id==='hall'&&state.receptionDone)nav.push(['foyer','回頭看看入口大門']);if(['window','room'].includes(id)&&!nav.some(([a])=>a==='desk'))nav.push(['desk','回到桌前']);return nav;};
const baseSceneCopy36=sceneCopy;
sceneCopy=function(id,from,revisited){if(id==='foyer'&&state.receptionDone)return '入口的厚門仍然合著。\n你已經試過門把，鎖沒有鬆開。';if(id==='room'&&state.keyReviewSuggested&&!state.keyTagRead)return '樓梯上已經沒有光，側廊的門仍鎖著，前廳也不見人影。\n你摸到口袋裡的鑰匙。懸著的金屬標牌……上面似乎有字。打開隨身物品，再看看吧。';if(id==='desk'&&!state.keyOwned&&!revisited&&!state.clues.includes('letter')&&!state.clues.includes('book')&&!state.drawerOpened&&!state.compartmentOpen)return '茶杯旁擱著一封未封口的信。\n露出的第一行寫著「致持邀請函而來的人」。是留給你的？';return baseSceneCopy36(id,from,revisited);};
const baseEntryLock36=inspectEntryLock;
inspectEntryLock=function(){if(!state.receptionDone){baseEntryLock36();return;}if(state.scene!=='foyer')go('foyer');showDialog('<p class="eyebrow">STILL LOCKED</p><h2>門依然沒有鬆開</h2>'+handlePicture('entry-handle-v21','再試試入口門把')+'<p id="entry-return-copy">你握住熟悉的提把，試著再壓下一點。</p><button id="entry-try" class="primary">再試一下門把</button><button id="entry-return" class="quiet">回到前廳</button>');$('entry-return').onclick=()=>{closeDialog();walk('hall')};$('entry-try').onclick=$('handle-picture').onclick=()=>playHandleMotion('urgent',()=>{$('entry-return-copy').textContent='又卡住了。門鎖仍牢牢扣著。看來，只能繼續找主人。';$('entry-try').hidden=true;});};
function candleArt(lit=true){return '<div class="held-candle '+(lit?'is-lit':'is-out')+'"><img src="assets/hand-candle-v36.png" alt="隨身的黃銅手燭"><canvas class="wick-flame" width="96" height="150" aria-hidden="true"></canvas></div>';}
function animateFlames(){if(!document.querySelectorAll)return;for(const canvas of document.querySelectorAll('.wick-flame')){if(canvas._flameRunning43)continue;const g=canvas.getContext('2d');if(!g)continue;canvas._flameRunning43=true;const epoch=beatEpoch;const frame=t=>{if(!canvas.isConnected||(!canvas.closest?.('.scene-candle43')&&(epoch!==beatEpoch||!$('detail').open))){canvas._flameRunning43=false;return;}g.clearRect(0,0,96,150);if(canvas.parentElement.classList.contains('is-lit')){const sway=reducedMotion()?0:Math.sin(t*.006)*5+Math.sin(t*.011)*2,h=85+(reducedMotion()?0:Math.sin(t*.009)*5),grad=g.createLinearGradient(48,135,48,135-h);grad.addColorStop(0,'#658ad7');grad.addColorStop(.18,'#fff6cf');grad.addColorStop(.65,'#ffc04b');grad.addColorStop(1,'#ffb93200');g.fillStyle=grad;g.beginPath();g.moveTo(48,139);g.bezierCurveTo(20,127,36,94,48+sway,135-h);g.bezierCurveTo(54+sway,100,78,130,48,139);g.fill();}requestAnimationFrame(frame)};requestAnimationFrame(frame);}}
function showHeldCandle(){showDialog('<p class="eyebrow">A LITTLE BORROWED LIGHT</p><h2>掌心裡的燭台</h2>'+candleArt(!state.candleOut||state.candleRenewed)+'<p>'+(state.candleOut&&!state.candleRenewed?'燭芯已經熄了。黃銅托盤仍留著一點餘溫。':(state.keyOwned||state.candleRenewed||candleIsLow()?'火苗隨你的呼吸輕輕搖晃，融蠟安靜地積在托盤裡。':'火苗隨你的呼吸輕輕搖晃，暖光映著黃銅托盤。'))+'</p><button id="held-put" class="primary">握穩提環，繼續探索</button>');animateFlames();$('held-put').onclick=closeDialog;}
const baseSurvey36=surveyEntry;surveyEntry=function(){if(state.candleHeld&&state.receptionDone){showHeldCandle();return;}baseSurvey36()};
const baseShowDialog36=showDialog;
showDialog=function(html,letter=false){const deskReturn=/A NOTE BENEATH THE LION|THE NIGHT LEDGER|獅像底座的便箋/.test(html)&&['room','desk','window'].includes(state.scene);baseShowDialog36(html+(deskReturn?'<button id="detail-desk-return" class="primary">回到桌前</button>':''),letter);if(deskReturn)$('detail-desk-return').onclick=()=>{closeDialog();if(state.scene!=='desk')walk('desk',true)};if(html.includes('id="take-entry-candle"')){const p=$('detail-body').querySelector?.('.photo-object');if(p)p.outerHTML=candleArt(true);animateFlames();}};
openInventory=function(){showDialog('<p class="eyebrow">WHAT YOU CARRY</p><h2>隨身物品</h2>'+(state.candleHeld?candleArt(!state.candleOut||state.candleRenewed)+'<p>玄關暫借的手燭。'+(state.candleRenewed?'已換上新蠟。':state.candleOut?'燭芯已經熄了。':'火焰仍輕輕晃動。')+'</p>':'')+(state.keyOwned?heldKeyArt(state.keyTagRead)+'<p>暫借的黃銅鑰匙，提環上懸著一枚金屬標牌。</p>':'<p>口袋裡還沒有其他物件。</p>')+(state.keyOwned&&(state.keyReviewSuggested||state.keyTagRead)?'<button id="inventory-tag" class="primary">'+(state.keyTagRead?'再看標牌上的方向':'翻看懸掛的金屬標牌')+'</button>':'')+(state.keyOwned&&state.scene==='door'&&state.corridorHandleTried&&!state.keyTried?'<button id="inventory-use" class="primary">這把鑰匙，會是開這扇門的嗎？</button>':'')+'<button id="inventory-close" class="quiet">收好物品</button>');animateFlames();if(state.keyOwned&&(state.keyReviewSuggested||state.keyTagRead))$('inventory-tag').onclick=inspectKeyTag;if(state.keyOwned&&state.scene==='door'&&state.corridorHandleTried&&!state.keyTried)$('inventory-use').onclick=tryKey;$('inventory-close').onclick=closeDialog;};$('inventory').onclick=openInventory;
const baseTag36=inspectKeyTag;inspectKeyTag=function(){if(!state.keyReviewSuggested&&!state.keyTagRead)return;baseTag36()};
function afterWrongKey(){state.keyTried=true;state.doorTried=true;save();storyBeats('身後的衣料聲',[{text:'你把鑰匙收回口袋。門後仍然沒有回答。\n正要退開時，身後響起兩段相接的摩擦，像衣襬拖過石面，又輕輕擦了一下。',action:'轉頭看向身後',wait:1300,sound:()=>{state.galleryHeard=true;save();firstCloth41()}}],()=>{state.finished=true;save();closeDialog();turnToGallery()});}
const baseTryHandle36=tryHandle;tryHandle=function(){if(state.keyTried&&!state.finished){afterWrongKey();return;}baseTryHandle36()};
const baseTurn36=turnToGallery;turnToGallery=async function(){await baseTurn36();if(state.scene==='gallery'&&!moving&&!state.clothRetreatHeard){state.clothRetreatHeard=true;save();quietFoley('cloth',.05,-.45);}};
function galleryChoices(){showDialog('<p class="eyebrow">BEYOND THE CANDLELIGHT</p><h2>現在，往哪裡找人？</h2><div class="gallery-depth">'+photoView('assets/gallery.webp','安靜的肖像長廊')+'</div><p>'+(state.stairSurveyDone?'樓梯上方已經沒有光。側廊那扇房門下，仍漏出一線暖色。':'你提穩快燃盡的手燭。樓梯上，似乎還有一點光。')+'</p><p>前廳那邊，'+(state.hallFootstepsHeard?'先前傳來的腳步已經停了。':'響起幾下很輕的腳步。有人經過了嗎？')+'</p><div class="gallery-options"><button id="gallery-stairs" class="primary">'+(state.stairSurveyDone?'再探照樓梯深處':'用燭光看看樓梯')+'</button><button id="gallery-door" class="primary">看看那扇亮著燈的房門</button><button id="gallery-footsteps" class="primary">回前廳，尋找腳步聲的主人</button></div>'+(keyReviewReady()?'<button id="gallery-study" class="primary">回書房，再想想其他線索</button>':''));if(!state.hallFootstepsHeard){state.hallFootstepsHeard=true;save();distantSteps();}$('gallery-stairs').onclick=()=>{closeDialog();if(state.scene==='stairwell')setupStairSurvey('stairwell');else walk('stairwell')};$('gallery-door').onclick=()=>{closeDialog();walk('door')};$('gallery-footsteps').onclick=()=>{closeDialog();walk('hall')};if(keyReviewReady())$('gallery-study').onclick=()=>{closeDialog();walk('room',true)};}
function afterStairChoices(){galleryChoices()}
const baseSetupStair36=setupStairSurvey;setupStairSurvey=function(id){baseSetupStair36(id);if(id==='stairwell'&&state.stairSurveyDone){$('stairs-finish').textContent='再看看其他地方吧';$('stairs-finish').onclick=galleryChoices;caption('上方的光已經熄了。你照過扶手與轉角，仍看不見人影。\n再看看其他地方吧。');}};
finishStairSurvey=function(){if(state.stairSurveyDone){galleryChoices();return;}if(state.scene!=='stairwell'||moving)return;state.stairsExplored=true;markExplored('stair-depth');storyBeats('朝樓梯望去',[{text:'你抬高快燃盡的燭台。\n上方那一點光，忽然熄了。',action:'護住燭火，再看看其他地方',wait:1500,enter:()=>{state.stairSurveyDone=true;state.galleryChoice='stairs';save();$('scene').src='assets/stairs-out-v36.webp';}}],galleryChoices);};
const baseSceneImage36=sceneImage;sceneImage=function(id){return id==='stairwell'&&state.stairSurveyDone?'assets/stairs-out-v36.webp':baseSceneImage36(id)};
function knockThree(){const epoch=beatEpoch;[0,620,1320].forEach(ms=>setTimeout(()=>{if(epoch===beatEpoch&&$('detail').open)sfx('knock')},ms/pace));}
function letterStage(settled=false){return '<div id="clue-motion" class="clue-motion letter-pull letter-v36 '+(settled?'playing settled':'')+'"><img class="motion-plate" src="assets/letter-plate-v29.webp" alt="桌上的信封"><canvas id="clue-paper" class="motion-piece" aria-label="致持邀請函而來的人"></canvas><img class="motion-envelope" src="assets/letter-plate-v29.webp" alt="八芒紋的未封口信封"></div>';}
async function mountLetter36(animate=false){const canvas=$('clue-paper'),panel=$('clue-motion'),epoch=beatEpoch;if(!canvas||!canvas.getContext)return;try{const photo=await loadPaperPhoto('assets/ledger-blank-v29.webp');await loadPaperPhoto('assets/letter-plate-v29.webp');if(document.fonts)await document.fonts.load('32px VelorneHand');if(epoch!==beatEpoch||!canvas.isConnected)return;const paper=makePaperTexture(photo,null),g=paper.getContext('2d');g.fillStyle='#39291b';g.textAlign='center';g.font='32px VelorneHand, cursive';letterWords.forEach((line,i)=>g.fillText(line,300,100+i*76,520));canvas.width=1672;canvas.height=941;paperQuad(canvas.getContext('2d'),paper,[{x:0,y:0},{x:600,y:0},{x:600,y:760},{x:0,y:760}],[{x:379,y:280},{x:1191,y:161},{x:1350,y:645},{x:431,y:774}]);panel.classList.add('paper-ready');if(animate){sfx('paper');panel.style.setProperty('--motion-time',(2.1/pace)+'s');panel.classList.add('playing');beatAfter(()=>{panel.classList.add('settled');$('motion-read').disabled=false;},2200/pace);}}catch{if(epoch===beatEpoch&&$('motion-read'))$('motion-read').disabled=false;}}
function inspectLetter(){if(state.clues.includes('letter')){note('letter');return;}showDialog('<p class="eyebrow">THE SAME INVITATION</p><h2>這封信，是給你的</h2>'+letterStage(false)+'<p>未封口的信封上，是邀請函同樣的八芒紋。<br>露出的稱呼寫著：「致持邀請函而來的人」。</p><button id="letter-extract" class="primary">抽出寫給自己的信</button><button id="letter-close" class="quiet">先回桌前</button>');mountLetter36();$('letter-extract').onclick=extractLetter;$('letter-close').onclick=closeDialog;}
function extractLetter(){showDialog('<p class="eyebrow">A NOTE FOR YOUR ARRIVAL</p><h2>慢慢抽出信紙</h2>'+letterStage(false)+'<p>你扶住信封，讓紙張沿著折口滑出來。</p><button id="motion-read" class="primary" disabled>讀一讀主人留下的話</button>');const epoch=beatEpoch;$('motion-read').disabled=true;$('motion-read').onclick=()=>{if(epoch===beatEpoch&&$('detail').open&&!$('motion-read').disabled)note('letter')};mountLetter36(true);if(typeof $('clue-paper').getContext!=='function')beatAfter(()=>{$('motion-read').disabled=false;},2200/pace);}
const baseNote36=note;note=function(id){if(id!=='letter'){baseNote36(id);return;}record('letter');rememberLine(notes.letter[0],notes.letter[1]);showDialog('<p class="eyebrow">S. V.</p><h2>循著光</h2>'+letterStage(true)+'<p>'+notes.letter[1].replaceAll('\n','<br>')+'</p><button id="putback" class="primary">收好這句話，回到桌前</button>');mountLetter36(false);$('putback').onclick=closeDialog;};
const baseCautious36=cautiousLook;cautiousLook=function(a){if(a==='letter'){inspectLetter();return true;}return baseCautious36(a)};
function animateNorthKey(){if(!northReady()||state.northUnlocked)return;showDialog('<p class="eyebrow">THE KEY FINDS ITS DOOR</p><h2>這一次，鑰匙進去了</h2><div id="key-lock-motion" class="lock-close36"><img src="assets/north-key-rest-v44.png" alt="鑰匙已插入玻璃門鎖，黃銅標牌向下懸掛"><canvas id="north-key-canvas" aria-hidden="true"></canvas></div><p id="key-motion-copy">你扶住鑰匙的提環。齒尖這次順利滑進去，沒有碰到阻礙。</p><button id="key-motion-start" class="primary">慢慢轉動鑰匙</button><button id="key-motion-cancel" class="quiet">先收回鑰匙</button>');quietFoley('key-insert',.24,.1);$('key-motion-cancel').onclick=closeDialog;let busy=false;const epoch=beatEpoch;$('key-motion-start').onclick=async()=>{if(busy||epoch!==beatEpoch)return;busy=true;$('key-motion-start').disabled=true;sfx('key');if(!await animateLock37(()=>epoch===beatEpoch&&$('detail').open))return;sfx('handle');state.northUnlocked=true;record('northKey');markExplored('north-lock');save();$('key-motion-copy').textContent='喀噠。鎖舌退開。你停住手，鑰匙留在轉開的位置。';$('key-motion-start').disabled=false;$('key-motion-start').textContent='收好鑰匙，慢慢向內推門';$('key-motion-start').onclick=pushGlassDoor;$('key-motion-cancel').textContent='先留在門前';};}
function pushGlassDoor(){if(!state.northUnlocked)return;showDialog('<p class="eyebrow">BEYOND THE GLASS</p><h2>向裡推開</h2><div id="glass-opening" class="glass-opening"><img class="glass-frame" src="assets/north-door-v32.webp" alt="北側門框"><div class="glass-interior"><img src="assets/glass-walk-v32.webp" alt="門後的玻璃廊"></div><img class="glass-leaf" src="assets/north-door-v32.webp" alt="沉重的玻璃門慢慢往內開"></div><p>你扶著門，讓它慢慢向裡退開。潮涼的空氣從門縫裡透出來。</p><button id="glass-step" class="primary" disabled>提著燭台走進去</button>');const epoch=beatEpoch;$('glass-step').disabled=true;setTimeout(()=>{if(epoch!==beatEpoch)return;$('glass-opening').classList.add('opening');sfx('creak')},60);beatAfter(()=>{$('glass-step').disabled=false;},reducedMotion()?0:3500/pace);$('glass-step').onclick=()=>{if(!$('glass-step').disabled)enterGlassWalk()};}
function renewCandle(){if(!state.lightPermission){readLightPermission();return;}if(state.candleRenewed){inspectLightShelf();return;}showDialog('<p class="eyebrow">BORROWING THE FLAME</p><h2>借一點火</h2><div id="flame-transfer">'+candleArt(false,true)+'</div><p id="flame-copy">你換好新蠟，將燭芯靠向油燈。掌心護住氣流。</p><button id="flame-start" class="primary">穩住燭芯，等火苗接過來</button><button id="flame-leave" class="quiet">先停下來</button>');animateFlames();const epoch=beatEpoch;let busy=false;$('flame-leave').onclick=closeDialog;$('flame-start').onclick=()=>{if(busy||epoch!==beatEpoch)return;busy=true;$('flame-start').disabled=true;const candle=$('flame-transfer').querySelector?.('.held-candle');if(candle)candle.classList.add('is-lit','catching');$('flame-copy').textContent='一點火星亮起，接著拉成小小的火焰。你等它站穩。';beatAfter(()=>{state.candleRenewed=true;state.candleOut=false;state.candleHeld=true;record('newLight');markExplored('light-shelf');save();$('stage').classList.remove('candle-out');$('flame-copy').textContent='亮了。光重新落在手背上。你把換下的短蠟放回托盤，提穩新燭。';$('flame-start').disabled=false;$('flame-start').textContent='握穩燭台，繼續探索';$('flame-start').onclick=()=>{closeDialog();caption(northCopy('glasswalk',true))};},2400/pace);};}
const baseGarden36=inspectGardenDoor;inspectGardenDoor=function(){baseGarden36();if(!state.candleRenewed||state.northAnswered)return;$('garden-listen').onclick=()=>storyBeats('這一次，聲音在等你',[{text:'叩、叩、叩。\n很輕，像指節碰在木框上。三聲之間，留著短短的停頓。',action:'望向雨中的玻璃',wait:2000,sound:knockThree},{text:'玻璃太暗，你看不清外面。\n聲音停下以後，對面也沒有離開的腳步。',action:'輕輕敲回三下',wait:1500},{text:'你屈起指節，把同樣的三聲送回去。\n「……請問，是這裡的主人嗎？」',action:'靜靜等候回應',wait:2200,sound:knockThree}],()=>{state.northAnswered=true;record('answeringKnock');markExplored('garden-door');save();northChapterEnd()});};
