/* A local, dependency-free WebGL object viewer. No model or network service required. */
window.createSealViewer=function(canvas,onDiscover){
 const gl=canvas.getContext('webgl',{alpha:true,antialias:true,preserveDrawingBuffer:false});
 if(!gl)throw new Error('WebGL unavailable');
 const vs=`attribute vec3 p;attribute vec3 n;attribute vec3 c;attribute vec2 uv;attribute float tex;uniform mat4 m;uniform mat4 projection;uniform mediump float distance;varying vec3 N;varying vec3 C;varying vec3 P;varying vec2 U;varying float T;void main(){vec4 q=m*vec4(p,1.);N=mat3(m)*n;C=c;P=q.xyz;U=uv;T=tex;q.z-=distance;gl_Position=projection*q;}`;
 const fs=`precision mediump float;varying vec3 N;varying vec3 C;varying vec3 P;varying vec2 U;varying float T;uniform sampler2D engraving;uniform mediump float distance;void main(){vec3 normal=normalize(N);vec3 v=normalize(vec3(0.,0.,distance)-P);vec3 key=normalize(vec3(-2.,3.,4.));vec3 fill=normalize(vec3(3.,.5,2.));vec3 rim=normalize(vec3(1.,2.,-3.));vec3 base=C;if(T>.5)base=texture2D(engraving,U).rgb;float kd=max(dot(normal,key),0.);float fd=max(dot(normal,fill),0.);float rd=max(dot(normal,rim),0.);float sp=pow(max(dot(normal,normalize(key+v)),0.),52.);float broad=pow(max(dot(normal,normalize(fill+v)),0.),15.);vec3 color=base*(.24+kd*.85+fd*.3)+vec3(1.,.78,.42)*sp*.8+vec3(.62,.73,.87)*broad*.22+vec3(.65,.40,.12)*rd*.36;gl_FragColor=vec4(pow(color,vec3(.85)),1.);}`;
 const resources=[];function shader(t,s){const sh=gl.createShader(t);gl.shaderSource(sh,s);gl.compileShader(sh);if(!gl.getShaderParameter(sh,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(sh));resources.push(['shader',sh]);return sh}
 const program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vs));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error('Shader link failed');gl.useProgram(program);
 const vertices=[];const brass=[.54,.32,.09],black=[.038,.035,.032],edge=[.7,.45,.17];
 function vertex(p,n,c,u=[0,0],t=0){vertices.push(...p,...n,...c,...u,t)}
 function lathe(profile,color,segments=96){for(let j=0;j<profile.length-1;j++){const [r0,y0]=profile[j],[r1,y1]=profile[j+1];const dy=y1-y0,dr=r1-r0,len=Math.hypot(dy,dr)||1;for(let k=0;k<segments;k++){const a=k/segments*Math.PI*2,b=(k+1)/segments*Math.PI*2;const pt=(r,y,t)=>[r*Math.cos(t),y,r*Math.sin(t)];const normal=t=>[dy/len*Math.cos(t),-dr/len,dy/len*Math.sin(t)];const A=pt(r0,y0,a),B=pt(r1,y1,a),C=pt(r1,y1,b),D=pt(r0,y0,b);for(const [p,n]of [[A,normal(a)],[C,normal(b)],[B,normal(a)],[A,normal(a)],[D,normal(b)],[C,normal(b)]])vertex(p,n,color)}}}
 // Revolved brass foot, collars, and turned ebony handle; all are volumetric meshes.
 lathe([[.54,-1.03],[.58,-1.01],[.6,-.96],[.6,-.82],[.57,-.78],[.48,-.76],[.38,-.64],[.19,-.57],[.19,-.5],[0,-.5]],brass);
 lathe([[.17,-.54],[.20,-.50],[.19,-.38],[.145,-.28],[.135,.05],[.15,.33],[.20,.58],[.28,.83],[.30,1.02],[.28,1.15],[.19,1.26],[0,1.31]],black);
 for(const y of [-.93,-.81,-.47,-.36])lathe([[.0,y-.015],[y<-.7?.603:.195,y-.015],[y<-.7?.603:.195,y+.015],[0,y+.015]],edge);
 lathe([[0,1.267],[.13,1.267],[.16,1.28],[.13,1.32],[0,1.33]],brass);
 // A textured bottom face is visible only after the object is turned over.
 for(let k=0;k<96;k++){const a=k/96*Math.PI*2,b=(k+1)/96*Math.PI*2;for(const q of [[0,-1.032,0],[.54*Math.cos(a),-1.032,.54*Math.sin(a)],[.54*Math.cos(b),-1.032,.54*Math.sin(b)]])vertex(q,[0,-1,0],brass,[q[0]/1.08+.5,q[2]/1.08+.5],1)}
 const buf=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buf);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(vertices),gl.STATIC_DRAW);let offset=0;for(const [name,size]of [['p',3],['n',3],['c',3],['uv',2],['tex',1]]){const loc=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,size,gl.FLOAT,false,48,offset*4);offset+=size}
 const ink=document.createElement('canvas');ink.width=ink.height=512;const pen=ink.getContext('2d');pen.fillStyle='#aa7b38';pen.fillRect(0,0,512,512);pen.strokeStyle='#49300f';pen.lineWidth=7;for(const r of [228,209]){pen.beginPath();pen.arc(256,256,r,0,Math.PI*2);pen.stroke()}pen.lineWidth=3;pen.beginPath();for(let i=0;i<16;i++){const a=i*Math.PI/8-Math.PI/2,r=i%2?25:i%4===0?120:76;const x=256+Math.cos(a)*r,y=219+Math.sin(a)*r;i?pen.lineTo(x,y):pen.moveTo(x,y)}pen.closePath();pen.stroke();pen.font='56px Georgia';pen.textAlign='center';pen.fillStyle='#422b10';pen.fillText('VII',256,370);pen.font='21px Georgia';pen.fillText('V E L O R N E',256,414);
 const texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,true);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,ink);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);
 const matrixLoc=gl.getUniformLocation(program,'m'),projLoc=gl.getUniformLocation(program,'projection'),distLoc=gl.getUniformLocation(program,'distance');gl.uniform1i(gl.getUniformLocation(program,'engraving'),0);gl.enable(gl.DEPTH_TEST);gl.clearColor(0,0,0,0);
 let x=.22,y=-.45,targetX=x,targetY=y,distance=4.8,raf,disposed=false,interacted=false,discovered=false,revealSince=0,pointer=null,settled=false;const listeners=[];function listen(type,fn){canvas.addEventListener(type,fn);listeners.push([type,fn])}
 function draw(time){if(disposed)return;const rect=canvas.getBoundingClientRect(),ratio=Math.min(window.devicePixelRatio||1,2);const w=Math.max(1,Math.round(rect.width*ratio)),h=Math.max(1,Math.round(rect.height*ratio));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;gl.viewport(0,0,w,h)}x+=(targetX-x)*.16;y+=(targetY-y)*.16;const cx=Math.cos(x),sx=Math.sin(x),cy=Math.cos(y),sy=Math.sin(y);const m=new Float32Array([cy,sx*sy,-cx*sy,0,0,cx,sx,0,sy,-sx*cy,cx*cy,0,0,0,0,1]);const f=1/Math.tan(.64/2),aspect=w/h;gl.uniformMatrix4fv(matrixLoc,false,m);gl.uniformMatrix4fv(projLoc,false,new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,-1.002,-1,0,0,-.2002,0]));gl.uniform1f(distLoc,distance);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);gl.drawArrays(gl.TRIANGLES,0,vertices.length/12);
 if(interacted&&!discovered&&-sx>.88){if(!revealSince)revealSince=time;if(time-revealSince>550){discovered=true;onDiscover()}}else revealSince=0;
 if(document.hidden){raf=setTimeout(()=>{raf=requestAnimationFrame(draw)},200)}else raf=requestAnimationFrame(draw)}
 listen('pointerdown',e=>{pointer={id:e.pointerId,x:e.clientX,y:e.clientY};canvas.setPointerCapture(e.pointerId);canvas.focus();interacted=true;canvas.classList.add('dragging')});listen('pointermove',e=>{if(!pointer||pointer.id!==e.pointerId)return;targetY+=(e.clientX-pointer.x)*.009;targetX+=(e.clientY-pointer.y)*.009;pointer.x=e.clientX;pointer.y=e.clientY});const release=e=>{if(pointer?.id===e.pointerId){pointer=null;canvas.classList.remove('dragging')}};listen('pointerup',release);listen('pointercancel',release);listen('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home'].includes(e.key)){e.preventDefault();interacted=true;if(e.key==='ArrowLeft')targetY-=.25;if(e.key==='ArrowRight')targetY+=.25;if(e.key==='ArrowUp')targetX-=.25;if(e.key==='ArrowDown')targetX+=.25;if(e.key==='Home'){targetX=.22;targetY=-.45}}});
 raf=requestAnimationFrame(draw);
 return{flip(){interacted=true;targetX=-Math.PI/2;targetY=0},reset(){targetX=.22;targetY=-.45;distance=4.8},zoom(amount){distance=Math.min(6,Math.max(3.5,distance+amount))},dispose(){disposed=true;cancelAnimationFrame(raf);clearTimeout(raf);for(const[t,fn]of listeners)canvas.removeEventListener(t,fn);gl.deleteBuffer(buf);gl.deleteTexture(texture);gl.deleteProgram(program);for(const[,s]of resources)gl.deleteShader(s);const ext=gl.getExtension('WEBGL_lose_context');ext?.loseContext()}};
};
